### ISSUE TITLE
Remove CSS references to controls.svg

### ISSUE THREAD

**Issue by artlogic** [arsmentis/wdet-conversion#126]
This is causing a lot of 404s, making managing redirects an issue.

**Comment by wdet30** [comment]
All set here.

**Comment by artlogic** [comment]
Still seeing a reference here:

```css
.mejs-controls .mejs-button button {
  cursor: pointer;
  display: block;
  font-size: 0;
  line-height: 0;
  text-decoration: none;
  margin: 7px 5px;
  padding: 0;
  position: absolute;
  height: 16px;
  width: 16px;
  border: 0;
  background: transparent url(controls.svg) no-repeat;
}

.no-svg .mejs-controls .mejs-button button {
  background-image: url(controls.png);
}
```
